language: ruby
rvm:
- 2.4.1
#script: "./bin/cibuild"

#env:
#  global:
#  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
#sudo: false
#cache: bundler
#notifications:
#  email: false


install:
- bundle install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: source