[build]
command = "pnpm build"
publish = "dist"

[[redirects]]
from = "/fr/*"
to = "/fr/404.html"
status = 404

[[plugins]]
package = "netlify-plugin-checklinks"

[plugins.inputs]
skipPatterns = ["dist/js/script.js"]
