export default {
  "/legal/notices": "/legal/legal-notices",
  "/legal/privacy": "/legal/privacy-policy",
  "/projects": "/#work",
  "/projects/nuxt3-starter-medusa": "/#work",
  "/projects/ohf31-website": "/#work",
  "/projects/ynotes-app": "/#work",
  "/projects/ynotes-website": "/#work",
  "/projects/ynotes-packages": "/#work",
  "/projects/cooker-ai": "/#work",
  "/projects/dumpus": "/#work",
  "/projects/glutton-runner": "/#work",
  "/projects/miyamoto": "/#work",
  "/projects/nuxt3-starter-template-for-medusa": "/#work",
  "/projects/ohf31": "/#work",
  "/projects/op-ent": "/#work",
  "/projects/portfolio": "/#work",
  "/projects/regiolangues": "/#work",
  "/projects/shortcuts-app": "/#work",
  "/projects/ynotes": "/#work",
  "/fr": "/",
  "/fr/a-propos": "/about",
  "/fr/blog": "/blog",
  "/fr/blog/annonce-de-choose-tech": "/blog/announcing-choose-tech",
  "/fr/blog/hydratation-dans-astro": "/blog/hydration-in-astro",
  "/fr/blog/mise-a-niveau-d-un-pc-sous-windows-10-non-pris-en-charge-vers-windows-11":
    "/blog/upgrading-an-unsupported-windows-10-pc-to-windows-11",
  "/fr/legal/mentions-legales": "/legal/legal-notices",
  "/fr/legal/politique-de-confidentialite": "/legal/privacy-policy",
  "/fr/projets": "/#work",
  "/fr/projets/cooker-ai": "/#work",
  "/fr/projets/dumpus": "/#work",
  "/fr/projets/glutton-runner": "/#work",
  "/fr/projets/miyamoto": "/#work",
  "/fr/projets/nuxt3-starter-template-for-medusa": "/#work",
  "/fr/projets/ohf31": "/#work",
  "/fr/projets/op-ent": "/#work",
  "/fr/projets/portfolio": "/#work",
  "/fr/projets/regiolangues": "/#work",
  "/fr/projets/shortcuts-app": "/#work",
  "/fr/projets/ynotes": "/#work",
};
